# Generated by Django 3.2 on 2021-04-25 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyGallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='post_date',
            field=models.DateTimeField(),
        ),
    ]
